name: npm publish package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}